# Generated by Django 6.0.3 on 2026-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth_user_gender_user_name_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
