# Generated by Django 6.0.4 on 2026-04-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_instagram_connected_user_instagram_username_and_more'),
        ('users', '0003_user_profile_image'),
    ]

    operations = [
    ]
