# Generated by Django 5.2.7 on 2026-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verification_token_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tiktok_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
