# Generated by Django 6.0.4 on 2026-04-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260413_2305'),
        ('users', '0006_user_tiktok_connected_user_tiktok_username'),
    ]

    operations = [
    ]
