# Generated by Django 5.2.7 on 2026-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('like', 'Like'), ('follow', 'Follow'), ('engagement', 'Engagement'), ('followers', 'New Followers'), ('activity', 'Activity Update')], default='admin', max_length=20),
        ),
    ]
