# Generated by Django 5.2.7 on 2026-04-13 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('videos_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('apify_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('videos_scraped', models.IntegerField(default=0)),
                ('engagement_percentage', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='tiktok_scraper.tiktokprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_videos', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('engagement_percentage', models.FloatField(default=0.0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
                ('average_likes_per_video', models.FloatField(default=0.0)),
                ('average_views_per_video', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tiktok_scraper.tiktokprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('video_url', models.URLField()),
                ('caption', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('video_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tiktok_scraper.tiktokprofile')),
            ],
            options={
                'ordering': ['-video_timestamp'],
            },
        ),
    ]
